travis:
  secure:
    BINSTAR_TOKEN: OJTJMbtAOkknc53uFzFZ45QOTuQNEVFKC8dOu2uo+LCZSVzzJPF3etq3ThWkaF1MOK+gsUOWmVFOcvQkc2Y71XbGTG1Zqqi5AqWWzDsoA7HcqdAMZU2GDZn7j7+XXAARPJVK0yo2FiPhyz6WaYIsCLTTsFzXhWvhn9yW2GsI7imzS8z/liJVl/EzxZmqx/tnaGE31BdarvOB4TW1QbxOznB8/9fAJTT0VBanIYum/LCb5TQyhU5g3P7aCPmvv6cOvGNvshZDInM4LqQ3ZVFucsix2ooPQ8pg97EpYmGccEbgHsDgnBvwE+9Lhp8idYKaa2hEE6T9o1s5WA/Aj8hf5VKSAK2TVURMu04ezLEdf/nE8JFiDJ29CaH5nr8U0hapW7033STYiIZzPqGA51//2OL1EDotgZAzfY0WX1dJAfxCavzK5LfGWnSsY+jJ8qr4vM+fAP3blqwuYYE12A1ey45+kaWUmxAcedZKmVIFBlodNTMqLxEG+M3Joh4inXSwOvBdQZKBsdo3EUKt1d6wFvTGU+wVDqdeMXS8rwhJw5E6WgDrq1VIFAzGese+yD2csS7xafL1szWwhtSzN9r9gSLys41Xj9aK3KLIeCurLfqHeL2MZ5NJ3gDMH50YaZSLG0P4dGSc+H9y2fLKncx5rIG4TaXUsBoeQybSYJ4zEjg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
