appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mTqZLizvh56Js7jJ6fIjtS0191nYbpqdnj8CRgQ0s+JL3hi0nAts8DeslKttxcgQr45f3QVgHKTzP2doQvD16BnEE/bVhJI67YE1UbvNjn5LUbJqBt1nItZiXBEWpum3GOC7RZ7JtdBS6BXf106lR7n9eFT4+GJwft6CFGqeaIYqLrstJEO1IdImJu4wldgv7SBFcNi4QJhOWF+9rPOqqxnGy4wsgCKs1FRhBnEQ7v/zBmJmEtMmFamwISpAqbAm3eRN9/y3xKOCJKOF+hbJAA9AFMZQ0I+zeRfHlxpI4AY8Co6v6xYgy7Wb5htsDumONypwchYZtLhPD6X+lkutvZBKEN/tXw/8A5vOAuyGpcN7JuzgxomKekuF1Z9oAqltbLVNfeAlKF04MZq5JwNQLIUUFJG/icf/HRVuR4mIpQA7CyIBEAXSfCD5PTIrDOgLBv8J3yAl5xyiTCrzdK+ulKc2VdWUn7XVWwC/uUsR4GgS4bJUF/h8Ijc6DRzpxD7VhT6MOug6MDLwndj+JQKWxU2oyRO+ugwOy+yTxapSaqzzTnaGiotCfF9H2qTz3droQYiJMFSNzzy8igrLgQug6cnTaOT2OzGcAXpbrX91vP4411tGd7LcxRhIq/Jm4ssG/v9mPPGfyPlBthVVI6K8N+OEp6bWPFVjp3LR6VsHgUA=}
conda_forge_output_validation: true
